linux-user: fix build with musl on aarch64
Use the standard uint64_t instead of internal __u64.

This fixes compiler error with musl libc on aarch64:
.../qemu-2.7.0/linux-user/host/aarch64/hostdep.h:28:5:
error: unknown type name '__u64'
     __u64 *pcreg = &uc->uc_mcontext.pc;
     ^~~~~

Signed-off-by: Natanael Copa <ncopa@alpinelinux.org>
Origin: https://git.alpinelinux.org/aports/plain/main/qemu/0001-linux-user-fix-build-with-musl-on-aarch64.patch
(cherry picked from commit 302bb58682d9bcb26b381d27cb4a323ee8d5fc65)